// Generate viem-typed ABI modules for the frontend from Hardhat artifacts.
//
// Run via `npm run generate:abis` (which compiles first). Plain Node ESM on
// purpose: this only reads artifact JSON and writes TS, so it needs no Hardhat
// runtime or ts-node. Output is committed and CI fails if it drifts from the
// compiled contracts (see .github/workflows/ci-evm.yml).
//
// To cover another contract, add an entry to CONTRACTS below.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const artifactsRoot = resolve(scriptDir, '../artifacts/contracts');
const outDir = resolve(scriptDir, '../../../web/src/generated/contracts');

// exportName -> artifact path (relative to contracts/evm/artifacts/contracts).
// Only the contracts the frontend actually calls. SmartRuntime is a diamond and
// is called through these facet ABIs at the runtime address, so it needs no
// separate binding.
const CONTRACTS = [
  { exportName: 'artistDirectoryAbi', file: 'artistDirectory', artifact: 'ArtistDirectory.sol/ArtistDirectory.json' },
  { exportName: 'artistRuntimeFactoryAbi', file: 'artistRuntimeFactory', artifact: 'ArtistRuntimeFactory.sol/ArtistRuntimeFactory.json' },
  { exportName: 'musicRegistryAbi', file: 'musicRegistry', artifact: 'pallets/MusicRegistryPallet.sol/MusicRegistryPallet.json' },
  { exportName: 'musicRoyaltiesAbi', file: 'musicRoyalties', artifact: 'pallets/MusicRoyaltiesPallet.sol/MusicRoyaltiesPallet.json' },
  { exportName: 'musicAccessAbi', file: 'musicAccess', artifact: 'pallets/MusicAccessPallet.sol/MusicAccessPallet.json' },
  { exportName: 'musicNFTAbi', file: 'musicNFT', artifact: 'pallets/MusicNFTPallet.sol/MusicNFTPallet.json' }
];

const HEADER = '// Auto-generated by contracts/evm/scripts/generate-abis.mjs. Do not edit manually.';

mkdirSync(outDir, { recursive: true });

for (const { exportName, file, artifact } of CONTRACTS) {
  const artifactPath = resolve(artifactsRoot, artifact);
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(artifactPath, 'utf8'));
  } catch {
    throw new Error(`Missing artifact ${artifact}. Run "npm run compile" first (generate:abis does this for you).`);
  }
  if (!Array.isArray(parsed.abi)) {
    throw new Error(`Artifact ${artifact} has no abi array.`);
  }
  const body = `${HEADER}\n// Source: contracts/evm/artifacts/contracts/${artifact}\n\nexport const ${exportName} = ${JSON.stringify(parsed.abi, null, 2)} as const;\n`;
  writeFileSync(resolve(outDir, `${file}.ts`), body);
}

const barrel = `${HEADER}\n\n${CONTRACTS.map(({ file }) => `export * from './${file}';`).join('\n')}\n`;
writeFileSync(resolve(outDir, 'index.ts'), barrel);

console.log(`Generated ${CONTRACTS.length} ABI modules + index into web/src/generated/contracts/`);
