import type { HardhatRuntimeEnvironment } from 'hardhat/types';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { defineChain, type Abi, type AbiFunction } from 'viem';
import { toFunctionSelector } from 'viem';

const ROOT_DIR = path.resolve(__dirname, '../../..');

export const DEPLOYMENTS_JSON = path.resolve(ROOT_DIR, 'deployments.json');
export const DEPLOYMENTS_TS = path.resolve(ROOT_DIR, 'web/src/config/deployments.ts');

export const POLKADOT_TESTNET_CHAIN = defineChain({
  id: 420420417,
  name: 'Polkadot Hub TestNet',
  nativeCurrency: { name: 'PAS', symbol: 'PAS', decimals: 18 },
  rpcUrls: { default: { http: ['https://eth-rpc-testnet.polkadot.io/'] } },
  blockExplorers: {
    default: { name: 'Blockscout', url: 'https://blockscout-testnet.polkadot.io/' }
  }
});

const PALLET_CONTRACTS = [
  ['cutPallet', 'DiamondCutPallet'],
  ['loupePallet', 'DiamondLoupePallet'],
  ['ownershipPallet', 'OwnershipPallet'],
  ['registryPallet', 'MusicRegistryPallet'],
  ['nftPallet', 'MusicNFTPallet'],
  ['royaltiesPallet', 'MusicRoyaltiesPallet'],
  ['accessPallet', 'MusicAccessPallet']
] as const;

type PalletDeploymentKey = (typeof PALLET_CONTRACTS)[number][0];
type PalletContractName = (typeof PALLET_CONTRACTS)[number][1];

export type SmartRuntimeDeployments = {
  factory: `0x${string}`;
  directory: `0x${string}`;
  initializer: `0x${string}`;
  pallets: Record<PalletDeploymentKey, `0x${string}`>;
};

export type SmartRuntimeDeploymentRecord = {
  factory: `0x${string}`;
  directory: `0x${string}`;
  initializer?: `0x${string}`;
  pallets: Partial<Record<PalletDeploymentKey, `0x${string}`>>;
};

type VerifyTarget = {
  label: string;
  address: `0x${string}`;
  constructorArguments?: readonly unknown[];
};

export function selectorsFromAbi(abi: Abi): `0x${string}`[] {
  return abi.filter((item): item is AbiFunction => item.type === 'function').map(fn => toFunctionSelector(fn));
}

export async function getDeployConfig(hre: HardhatRuntimeEnvironment) {
  if (hre.network.name !== 'polkadotTestnet') {
    return {};
  }

  const publicClient = await hre.viem.getPublicClient({ chain: POLKADOT_TESTNET_CHAIN });
  const [wallet] = await hre.viem.getWalletClients({ chain: POLKADOT_TESTNET_CHAIN });
  if (!wallet) {
    throw new Error('No deployer account. Set one with: npx hardhat vars set PRIVATE_KEY');
  }

  return { client: { public: publicClient, wallet } };
}

export async function buildFactorySelectors(hre: HardhatRuntimeEnvironment): Promise<`0x${string}`[][]> {
  const selectors: `0x${string}`[][] = [];

  for (const [, contractName] of PALLET_CONTRACTS) {
    const artifact = await hre.artifacts.readArtifact(contractName);
    selectors.push(selectorsFromAbi(artifact.abi as Abi));
  }

  return selectors;
}

export async function buildFactoryConstructorArguments(hre: HardhatRuntimeEnvironment, deployments: SmartRuntimeDeployments): Promise<readonly unknown[]> {
  const selectors = await buildFactorySelectors(hre);

  return [
    deployments.directory,
    deployments.initializer,
    deployments.pallets.cutPallet,
    deployments.pallets.loupePallet,
    deployments.pallets.ownershipPallet,
    deployments.pallets.registryPallet,
    deployments.pallets.nftPallet,
    deployments.pallets.royaltiesPallet,
    deployments.pallets.accessPallet,
    selectors
  ] as const;
}

export function writeDeployments(data: SmartRuntimeDeployments) {
  fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + '\n');

  const ts = `// AUTO-GENERATED by contracts/evm/scripts/deploy.ts — do not edit manually
export const deployments = ${JSON.stringify(data, null, 2)} as const;

export type Deployments = typeof deployments;
`;

  fs.writeFileSync(DEPLOYMENTS_TS, ts);
  console.log('  ✓ deployments.json + web/src/config/deployments.ts written');
}

export function readDeployments(): SmartRuntimeDeploymentRecord {
  return JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, 'utf8')) as SmartRuntimeDeploymentRecord;
}

export async function hydrateDeploymentsFromChain(hre: HardhatRuntimeEnvironment, record: SmartRuntimeDeploymentRecord): Promise<SmartRuntimeDeployments> {
  if (hasCompleteDeployments(record)) {
    return record;
  }

  const cfg = await getDeployConfig(hre);
  const factory = await hre.viem.getContractAt('ArtistRuntimeFactory', record.factory, cfg);

  const [directory, initializer, cutPallet, loupePallet, ownershipPallet, registryPallet, nftPallet, royaltiesPallet, accessPallet] = (await Promise.all([
    factory.read.directory(),
    factory.read.initContract(),
    factory.read.cutPallet(),
    factory.read.loupePallet(),
    factory.read.ownershipPallet(),
    factory.read.registryPallet(),
    factory.read.nftPallet(),
    factory.read.royaltiesPallet(),
    factory.read.accessPallet()
  ])) as [`0x${string}`, `0x${string}`, `0x${string}`, `0x${string}`, `0x${string}`, `0x${string}`, `0x${string}`, `0x${string}`, `0x${string}`];

  return {
    factory: record.factory,
    directory: record.directory ?? directory,
    initializer: record.initializer ?? initializer,
    pallets: {
      cutPallet: record.pallets.cutPallet ?? cutPallet,
      loupePallet: record.pallets.loupePallet ?? loupePallet,
      ownershipPallet: record.pallets.ownershipPallet ?? ownershipPallet,
      registryPallet: record.pallets.registryPallet ?? registryPallet,
      nftPallet: record.pallets.nftPallet ?? nftPallet,
      royaltiesPallet: record.pallets.royaltiesPallet ?? royaltiesPallet,
      accessPallet: record.pallets.accessPallet ?? accessPallet
    }
  };
}

export async function verifySmartRuntimeSystem(
  hre: HardhatRuntimeEnvironment,
  deployments: SmartRuntimeDeployments,
  options: { delayMs?: number; attempts?: number } = {}
) {
  if (hre.network.name !== 'polkadotTestnet') {
    console.log('\nSkipping verification on non-testnet network.');
    return;
  }

  const delayMs = options.delayMs ?? 15_000;
  const attempts = options.attempts ?? 3;

  console.log(`\nWaiting ${Math.round(delayMs / 1000)}s for explorer indexing before verification...`);
  await sleep(delayMs);

  const verifyTargets: VerifyTarget[] = [
    { label: 'DiamondCutPallet', address: deployments.pallets.cutPallet },
    { label: 'DiamondLoupePallet', address: deployments.pallets.loupePallet },
    { label: 'OwnershipPallet', address: deployments.pallets.ownershipPallet },
    { label: 'MusicRegistryPallet', address: deployments.pallets.registryPallet },
    { label: 'MusicNFTPallet', address: deployments.pallets.nftPallet },
    { label: 'MusicRoyaltiesPallet', address: deployments.pallets.royaltiesPallet },
    { label: 'MusicAccessPallet', address: deployments.pallets.accessPallet },
    { label: 'DotifyRuntimeInitializer', address: deployments.initializer },
    { label: 'ArtistDirectory', address: deployments.directory },
    {
      label: 'ArtistRuntimeFactory',
      address: deployments.factory,
      constructorArguments: await buildFactoryConstructorArguments(hre, deployments)
    }
  ];

  console.log('\nVerifying deployed contracts on Blockscout...');
  for (const target of verifyTargets) {
    await verifyContract(hre, target, attempts);
  }
  console.log('  ✓ Verification complete');
}

async function verifyContract(hre: HardhatRuntimeEnvironment, target: VerifyTarget, attempts: number) {
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      await hre.run('verify:verify', {
        address: target.address,
        constructorArguments: target.constructorArguments ?? []
      });
      console.log(`  ✓ ${target.label} verified`);
      return;
    } catch (error) {
      const message = getErrorMessage(error);

      if (/already verified|already been verified|contract source code already verified/i.test(message)) {
        console.log(`  ↺ ${target.label} already verified`);
        return;
      }

      if (attempt < attempts && shouldRetryVerification(message)) {
        console.log(`  … ${target.label} verification attempt ${attempt}/${attempts} failed. Retrying in 10s.\n    ${firstLine(message)}`);
        await sleep(10_000);
        continue;
      }

      throw new Error(`${target.label} verification failed: ${message}`);
    }
  }
}

function shouldRetryVerification(message: string) {
  return /bytecode|fetch failed|request failed|not found|timed out|temporary|pending|unable to/i.test(message);
}

function getErrorMessage(error: unknown) {
  if (error instanceof Error) {
    return error.message;
  }

  return String(error);
}

function firstLine(message: string) {
  return message.split('\n')[0] ?? message;
}

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function hasCompleteDeployments(record: SmartRuntimeDeploymentRecord): record is SmartRuntimeDeployments {
  return Boolean(
    record.initializer &&
    record.pallets.cutPallet &&
    record.pallets.loupePallet &&
    record.pallets.ownershipPallet &&
    record.pallets.registryPallet &&
    record.pallets.nftPallet &&
    record.pallets.royaltiesPallet &&
    record.pallets.accessPallet
  );
}

export { PALLET_CONTRACTS, type PalletContractName };
