import { RefreshCw } from 'lucide-react';
import type { EarningsHistoryState } from '../../features/artist-studio/earnings';
import { formatWeiAsDot } from '../../shared/utils/format';

export type EarningsSummaryProps = {
  generatedWei: bigint;
  receivedWei: bigint;
  claimableWei: bigint;
  claimableKnown: boolean;
  historyState: EarningsHistoryState;
  updatedAt: number | null;
  refreshing: boolean;
  symbol: string;
  onRefresh: () => void;
};

export function EarningsSummary({
  generatedWei,
  receivedWei,
  claimableWei,
  claimableKnown,
  historyState,
  updatedAt,
  refreshing,
  symbol,
  onRefresh
}: EarningsSummaryProps) {
  const known = updatedAt !== null;
  const amount = (value: bigint, available = known) =>
    available ? `${formatWeiAsDot(value)} ${symbol}` : historyState === 'unavailable' ? 'Unavailable' : 'Checking...';
  return (
    <section className='studio-earnings' aria-label='Release earnings'>
      <div className='studio-section-head'>
        <h2>Earnings</h2>
        <div className='earnings-freshness'>
          <span role='status'>
            {historyState === 'stale'
              ? 'Update delayed'
              : historyState === 'unavailable'
                ? 'History unavailable'
                : refreshing
                  ? 'Checking payments...'
                  : updatedAt
                    ? `Checked ${new Date(updatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}`
                    : 'Waiting for payment history'}
          </span>
          <button className='icon-button' type='button' onClick={onRefresh} disabled={refreshing} aria-label='Refresh earnings' title='Refresh earnings'>
            <RefreshCw size={17} className={refreshing ? 'spin' : undefined} />
          </button>
        </div>
      </div>
      <dl className='earnings-totals'>
        <div>
          <dt>Generated by your releases</dt>
          <dd>{amount(generatedWei)}</dd>
        </div>
        <div>
          <dt>Received by you</dt>
          <dd>{amount(receivedWei)}</dd>
        </div>
        <div>
          <dt>Available to claim</dt>
          <dd>{claimableKnown ? amount(claimableWei, true) : 'Unavailable'}</dd>
        </div>
      </dl>
      <details className='earnings-definition'>
        <summary>About these amounts</summary>
        <p>
          Release revenue includes all recipients. Received is your settled share, including collaborations. Available to claim is still held for your account.
          Direct gifts and network fees are not included.
        </p>
        <p>
          Payments are checked every 15 seconds while this space is visible. A delayed update keeps the last complete reading. Older access receipts can prove
          revenue without proving its recipient settlement.
        </p>
      </details>
    </section>
  );
}
