// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// Auto-generated by cdm install. Do not edit by hand.
// CDM package: @dotify/artist-runtime-factory
// CDM version: 0

interface IDotifyArtistRuntimeFactory {
    event ArtistRuntimeBootstrapStarted(address indexed artist, address indexed runtime);
    event ArtistRuntimeBootstrapStep(address indexed artist, address indexed runtime, uint8 indexed completedStage);
    event ArtistRuntimeCreated(address indexed artist, address indexed runtime);
    function accessPallet() external view returns (address);
    function createRuntime() external returns (address);
    function cutPallet() external view returns (address);
    function directory() external view returns (address);
    function initContract() external view returns (address);
    function installRuntimeStep() external returns (uint8);
    function loupePallet() external view returns (address);
    function nftPallet() external view returns (address);
    function ownershipPallet() external view returns (address);
    function pendingRuntimeOf(address arg0) external view returns (address);
    function pendingRuntimeStageOf(address arg0) external view returns (uint8);
    function registryPallet() external view returns (address);
    function royaltiesPallet() external view returns (address);
    function runtimeOf(address artist) external view returns (address);
}

library DotifyArtistRuntimeFactory {
    address internal constant ADDRESS = 0xBd1a11cFcE8B5Ef7a37E507bC5109895F8F42a72;

    function ref() internal pure returns (IDotifyArtistRuntimeFactory) {
        return IDotifyArtistRuntimeFactory(ADDRESS);
    }

    function cdm() internal pure returns (IDotifyArtistRuntimeFactory) {
        return ref();
    }
}
