// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// Auto-generated by cdm install. Do not edit by hand.
// CDM package: @dotify/artist-directory
// CDM version: 0

interface IDotifyArtistDirectory {
    event ArtistRegistered(address indexed artist, address indexed runtime);
    event FactorySet(address indexed factory);
    function artistAtIndex(uint256 index) external view returns (address);
    function artistCount() external view returns (uint256);
    function artistsPage(uint256 offset, uint256 limit) external view returns (address[] memory, address[] memory);
    function deployer() external view returns (address);
    function factory() external view returns (address);
    function register(address artist, address runtime) external;
    function runtimeOf(address arg0) external view returns (address);
    function setFactory(address _factory) external;
}

library DotifyArtistDirectory {
    address internal constant ADDRESS = 0xcf1534C6e2B0E43B9436c1e86A076466dC0F2108;

    function ref() internal pure returns (IDotifyArtistDirectory) {
        return IDotifyArtistDirectory(ADDRESS);
    }

    function cdm() internal pure returns (IDotifyArtistDirectory) {
        return ref();
    }
}
