// Auto-generated by cdm install -- do not edit
import type { HexString, SizedHex } from "polkadot-api";

declare module "@parity/cdm-codegen" {
    interface CdmContracts {
        "@dotify/artist-directory": {
            methods: {
                artistAtIndex: { args: [index: bigint]; response: HexString };
                artistCount: { args: []; response: bigint };
                artistsPage: { args: [offset: bigint, limit: bigint]; response: { artists: HexString[]; runtimes: HexString[] } };
                deployer: { args: []; response: HexString };
                factory: { args: []; response: HexString };
                register: { args: [artist: HexString, runtime: HexString]; response: undefined };
                runtimeOf: { args: [arg0: HexString]; response: HexString };
                setFactory: { args: [_factory: HexString]; response: undefined };
            };
        };
        "@dotify/artist-runtime-factory": {
            methods: {
                accessPallet: { args: []; response: HexString };
                createRuntime: { args: []; response: HexString };
                cutPallet: { args: []; response: HexString };
                directory: { args: []; response: HexString };
                initContract: { args: []; response: HexString };
                installRuntimeStep: { args: []; response: number };
                loupePallet: { args: []; response: HexString };
                nftPallet: { args: []; response: HexString };
                ownershipPallet: { args: []; response: HexString };
                pendingRuntimeOf: { args: [arg0: HexString]; response: HexString };
                pendingRuntimeStageOf: { args: [arg0: HexString]; response: number };
                registryPallet: { args: []; response: HexString };
                royaltiesPallet: { args: []; response: HexString };
                runtimeOf: { args: [artist: HexString]; response: HexString };
            };
        };
    }
}
