// AUTO-GENERATED by contracts/evm/scripts/deploy.ts — do not edit manually
export const deployments = {
  "factory": "0x5d16ee1e9c02c52872b979c24b1fe906be58f4fb",
  "directory": "0x9f42a68b0c618f0f3a8a6c7c73e2c5ce1c180976",
  "initializer": "0x1ad9da133cc0a4df91efe2521c7df9f731964195",
  "pallets": {
    "cutPallet": "0xaab2f8304f1a02892f62eb50cfbd43eaca89ca7d",
    "loupePallet": "0xb2590210148846394c3d895f580b40ec1dd76025",
    "ownershipPallet": "0xf24027a67348934eaf9d071d7c2f9c162c06aeec",
    "registryPallet": "0xfbd5b3293ef164ade1490056e196411c23c8ecac",
    "nftPallet": "0x7138b91c007bb331a7a80d5eaaa03da5841f8893",
    "royaltiesPallet": "0x11a5b56b6ef86bdaeaa0d93dcc2cca02947c6a87",
    "accessPallet": "0x5a24ed575511df37b6527dbd545c0d45871bd662"
  }
} as const;

export type Deployments = typeof deployments;
