// AUTO-GENERATED by contracts/evm/scripts/deploy.ts — do not edit manually
export const deployments = {
  "factory": "0x66cd9f2d6cfed3b34d929e5b0c0c893eda01eb62",
  "directory": "0x9a0e42a5c32ea6ef2697c1af7481cce090217983",
  "initializer": "0x78f93bd1267b3196cf5d8bff7b168e0e34ec7b28",
  "pallets": {
    "cutPallet": "0xa507b00463ce82df6a105ab05f810809faedd538",
    "loupePallet": "0xaab840aae52da8485456bad7cc0c707cf91f7a3e",
    "ownershipPallet": "0xfb137042368c2884d3439f05e8b7b3dcdde838a3",
    "registryPallet": "0x8a363b18f95788c4781ac3486d5748084acb2f95",
    "nftPallet": "0xee8f07ddf0275622943f5348c44ab881ab5ddedb",
    "royaltiesPallet": "0x1e14ed0a017e8d70576d863eac38694334e2a605",
    "accessPallet": "0xdc537af8186ff151c5b5beb68fa19f6df58fd246"
  }
} as const;

export type Deployments = typeof deployments;
