// AUTO-GENERATED by contracts/evm/scripts/deploy.ts — do not edit manually
export const deployments = {
  factory: '0x9337287a194dfd8b53939eee1890b3f4ec0f8b0d',
  directory: '0xda2761fea6f0871ed44ec719860fddb51b115be8',
  initializer: '0xe0489b6128954c92b1d878596df97d5b2aca378d',
  pallets: {
    cutPallet: '0xf0ebaf0c7f6c69eb9ac6059e24ace6b1d4fcd133',
    loupePallet: '0xb521203652ce8dfb0f5488d178f2963cd28ff8bd',
    ownershipPallet: '0xcee8f69b48588120081cb1a1bbd2ca07c50f0ea3',
    registryPallet: '0x76ac102f448fbab9a7ea9efe4450878c01aabc8d',
    nftPallet: '0xb43be8d7b2c9bcc143187aafd3bbcd4a88e5e7f6',
    royaltiesPallet: '0x37371e77670c96b436e5c2fa55cb949578039dea',
    accessPallet: '0x13d9148c6d483952676343d9b1c5eb4ffe97cad5'
  }
} as const;

export type Deployments = typeof deployments;
