// AUTO-GENERATED by contracts/evm/scripts/deploy.ts — do not edit manually
export const deployments = {
  factory: '0x3490b3e5e7c1f696c61fde1c2679725b19274b0e',
  directory: '0xde4fcf30b2284243d44a7ccae862c4781196e01e',
  initializer: '0xed25715f30074cfb33859193f4386115005a9c2a',
  pallets: {
    cutPallet: '0x717f7453283bcc80f924c010cc1c73a5c80971ba',
    loupePallet: '0x7e125119186fd2d48e05613a866636364945372b',
    ownershipPallet: '0xa4b52c2162759e4e6db59d75a8dfc6cb4d5d29f6',
    registryPallet: '0x7c8203011bccd0ef8122cfbcaa570fe8f78dce38',
    nftPallet: '0x92c152111207f9cf05fdcdcceef54d5975247e3c',
    royaltiesPallet: '0x03936eabbe5149f3d4e9b8c273d1f362ef72ec39',
    accessPallet: '0x9c667f70cb6087a1413a89002765ef0ee2883da1'
  }
} as const;

export type Deployments = typeof deployments;
