// AUTO-GENERATED by contracts/evm/scripts/deploy.ts — do not edit manually
export const deployments = {
  factory: '0xae4e76eced8205c8afcbd7f391bde2032445dd67',
  directory: '0x3585707a2490ecc5aae25d54090da6ca5229f597',
  initializer: '0x70b337de85b28372dc7391fc24e441d5b922c693',
  pallets: {
    cutPallet: '0x607fd001490f8c380c3f8ecf64d675d4f17d2efd',
    loupePallet: '0x5705187a6763e7e9f99d949f13709541212a7cef',
    ownershipPallet: '0x8d6e1cae08dde069b7ceef93bb18c9d44f28b20c',
    registryPallet: '0x76dfb41711d8a0b6075ac79afa6868b4a01a0105',
    nftPallet: '0xf7a3e3e4f395c58d3ded831960a7e43c5826e82d',
    royaltiesPallet: '0xf6dc2ff7e47214d7a5ed8cd866b2691255ef56f3',
    accessPallet: '0x375843af6aa00f365d87e2c1d24c737689a557b1'
  }
} as const;

export type Deployments = typeof deployments;
