// Generated by npm run generate:product-catalog-bootstrap. Do not edit manually.
import type { CatalogApiResponse } from './catalog';

export const PRODUCT_DEVNET_BOOTSTRAP_PRODUCT_ID = 'dotify-test01.dot';

export const PRODUCT_DEVNET_BOOTSTRAP_CATALOG: CatalogApiResponse = {
  items: [],
  artists: [],
  pagination: {
    limit: 100,
    nextCursor: null,
    total: 0
  },
  meta: {
    state: 'stale-cache',
    cacheAvailable: true,
    indexedAt: '2026-09-06T12:00:00.000Z',
    lastIndexedBlock: 13103317,
    chainHeadBlock: 13103319,
    blockLag: 2,
    staleAfterMs: 60000,
    lastErrorCode: null
  }
};
